
name: Update Website

on: push
  # release:
  #   types: [published]

jobs:
  update-website:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          path: website
          repository: IrosTheBeggar/mStream
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      - name: edit
        uses: battila7/get-version-action@v2
      - run: echo test
      - run: ls
      - run: ls website
      - run: cd website
      - run: echo ${{ steps.get_version.outputs.version }}
      - run: |
          echo ${{ steps.get_version.outputs.version }}
          sed -i 's/[1-9]\+[0-9]*\.[0-9]\+\.[0-9]\+/${{ steps.get_version.outputs.version-without-v }}/g' website/templates/express.html
          git config user.name github-actions
          git config user.email github-actions@github.com
          git commit -m "action: update server"
          git push


