
name: Update Website

on: push
  # release:
  #   types: [published]

jobs:
  update-website:
    runs-on: ubuntu-latest
    steps:
      - name: checkout 1
        uses: actions/checkout@v2
        with:
          path: website
          repository: IrosTheBeggar/mstream-website
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      - name: checkout 2
        uses: actions/checkout@v2
        with:
          path: mstream
          repository: IrosTheBeggar/mStream
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      - run: |
        cd mstream
        git fetch --all --tags
      - name: edit
        uses: thebongy/version-check@v1
        with:
          file: mstream/package.json
          failBuild: false
      - run: ls
      - run: echo "Version ${{steps.version_check_staging.outputs.releaseVersion}}"
      - run: |
          cd website
          echo ${{ steps.get_version.outputs.version }}
          sed -i 's/[1-9]\+[0-9]*\.[0-9]\+\.[0-9]\+/${{ steps.version_check_staging.outputs.releaseVersion }}/g' templates/express.html
          # git config user.name github-actions
          # git config user.email github-actions@github.com
          # git add .
          # git commit -m "action: update server"
          # git push
          cat templates/express.html


